### ISSUE TITLE
digital induction reasoning A has two different standard score

### ISSUE THREAD

**Issue by Blockhead-yj** [psychelzh/tarflow.iquizoo#19]
It seems that same game score will generate two different standard score on different game time.

**Comment by psychelzh** [comment]
I think this should be on [tower.im](https://tower.im/). Please add it there.

**Comment by psychelzh** [comment]
See this for example:

![image](https://user-images.githubusercontent.com/13306020/112964795-391ae180-917b-11eb-8130-c6c99d3c0b45.png)

**Comment by Blockhead-yj** [comment]
No, the question in tower is in mgr.iquizoo, but this question is from tarflow.iquizoo. It comes from the scripts of tarflow.iquizoo

**Comment by psychelzh** [comment]
Got it. That means you suspect it is the query file or something to be blame for this. I think it is time to review the codes now.

**Comment by psychelzh** [comment]
And what type of schema did you use?

**Comment by Blockhead-yj** [comment]
now we find that the reason is there are more than one content ability ID for some game, thus use different norms.

we can add one column content ability ID to identify.
