### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by psychelzh** [psychelzh/tarflow.iquizoo#27]
It is often not good to change package names, but currently the name is too long.

Some alternatives:

* {tar.iquizoo}
* {tar.iq}
* {tarflow}

The third can be good, but it is not suitable for this workflow generation is just for iquizoo.

@Blockhead-yj  Have you got any ideas?

**Comment by Blockhead-yj** [comment]
i vote for tar.iqz

**Comment by Blockhead-yj** [comment]
or tar.iquizoo

**Comment by psychelzh** [comment]
So the short of *iquizoo* is taken *iqz*. This basic logic can be favorable.

**Comment by psychelzh** [comment]
No more hesitation.
