### ISSUE TITLE
Error in key(".id") : could not find function "key"

### ISSUE THREAD

**Issue by Blockhead-yj** [psychelzh/tarflow.iquizoo#33]
there is a syntax error in _targets.    key(".id")

**Comment by psychelzh** [comment]
Found these lines cause this error:

https://github.com/psychelzh/tarflow.iquizoo/blob/0807fd10bfb75b5ff9bfad62421ece9a23b8616a/R/steps.R#L121-L124

**Comment by Blockhead-yj** [comment]
a similar problem: Error : unused argument (by = key)  in function wrangle_data.
